# 网关
gateway: codetube
# 监听重载配置间隔
watch-interval-seconds: 5
# 默认监听信息
listen:
  # 默认监听主机
  host: localhost
  # 默认监听端口
  port: 8088
# MySQL 数据库连接信息
mysql:
  # 主机
  host:
  # 端口
  port: 3306
  # 数据库
  database:
  # 账号
  username:
  # 密码
  password:
  # 最大空闲数
  maxidle: 5
  # 最大连接数
  maxopen: 10